//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanDoChoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.NhaSanXuats = new HashSet<NhaSanXuat>();
        }
    
        public string MaSP { get; set; }
        public string MaLoaiSP { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
        public int GiaTien { get; set; }
        public int GiaNhap { get; set; }
        public int SoLuong { get; set; }
        public int LoiNhuan { get; set; }
        public int KhuyenMai { get; set; }
        public string TinhTrang { get; set; }
        public byte[] HinhAnh { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaSanXuat> NhaSanXuats { get; set; }
    }
}
